name: sticker_creator
description: Flutter app for create stickers

version: 0.0.1+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Architecture
  bloc: ^8.0.1
  flutter_bloc: ^8.0.0

  #DI
  provider: ^6.0.1

  #Navigation
  auto_route: ^3.2.0

  #Utils
  intl: ^0.17.0
  freezed: ^0.15.0+1
  freezed_annotation: ^0.15.0
  json_annotation: ^4.4.0
  rxdart: ^0.27.2
  url_launcher: ^6.0.17
  flutter_localizations:
    sdk: flutter 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.0.1
  json_serializable: ^6.1.0
  retrofit_generator: ^2.2.0
  build_runner: ^2.1.5
  test: ^1.17.12

flutter:
  uses-material-design: true
  assets:
    - assets/images/png/
    - assets/images/svg/

    
flutter_intl:
  enabled: true

